[package]
name                    = "emacs-regexp-ffi"
description             = "C ABI interface to expose to C code such as emacs."
version                 = "0.0.0"
edition.workspace       = true
license                 = "GPL-3.0-or-later"
repository.workspace    = true
authors.workspace       = true

[dependencies]

[dev-dependencies]

[lints]
workspace               = true
