[workspace]
members                 = [
    ".",
    "syntax",
]
default-members         = [
    ".",
    # "syntax",
]
resolver                = "2"

[workspace.package]
edition                 = "2021"
repository              = "https://github.com/cosmicexplorer/emacs-regexp"
authors                 = ["Danny McClanahan <dmcC2@hypnicjerk.ai>"]

[workspace.dependencies]
emacs-regexp-syntax     = { path = "./syntax" }

[workspace.lints.clippy]
len_without_is_empty    = "allow"
redundant_field_names   = "allow"
too_many_arguments      = "allow"
single_component_path_imports = "allow"
module_inception        = "allow"
match_ref_pats          = "allow"
expl_impl_clone_on_copy = "deny"
if_not_else             = "deny"
needless_continue       = "deny"
unseparated_literal_suffix = "deny"
used_underscore_binding = "deny"
collapsible_else_if     = "allow"
result_large_err        = "allow"

[package]
name                    = "emacs-regexp"
description             = "Implementation of emacs regexp matching!"
version                 = "0.0.0"
edition.workspace       = true
license                 = "GPL-3.0-or-later"
repository.workspace    = true
authors.workspace       = true

[lib]
name                    = "rex"

[dependencies]
# emacs-regexp-syntax.workspace = true
# aho-corasick            = "1.1.2"
hashbrown               = { version = "0.14", default-features = false, features = ["nightly", "inline-more"] }
indexmap                = { version = "2.2.6", default-features = false, features = [] }
# memchr                  = "2.7.1"
memchr                  = { git = "https://github.com/cosmicexplorer/memchr", rev = "091a2ecbf84614bb215d3ec17acb856a8eca566d" }
# memchr                  = { path = "/home/cosmicexplorer/tools/memchr" }
rustc-hash              = "1.1.0"
smallvec                = { version = "2.0.0-alpha.4", features = ["specialization", "may_dangle"] }
static_assertions       = "1.1.0"
# FIXME: hw acceleration for AVX2? https://docs.rs/xxhash-rust/latest/xxhash_rust/#hw-acceleration
xxhash-rust             = { version = "0.8.10", features = ["xxh3", "const_xxh3"] }

[build-dependencies]

[dev-dependencies]

[lints]
workspace               = true
